### ISSUE TITLE
get_layer_outputs() assumes tf ordering

### ISSUE THREAD

**Issue by isaacgerg** [jakebian/quiver#20]
get_layer_outputs() assumes tf ordering when deciding how many tiles are in an output.  in 84... "for z in range(0, layer_outputs.shape[2]) "

layer_outputs.shape[2] only valid for tf, for theano, use layer_outputs.shape[0]

Also, `img = layer_outputs[:,:,z]` is tf dependent.  Should be `img = layer_outputs[z,:,:]` for theano.

**Comment by dan-1d** [comment]
I submitted a pull request that should fix this.

**Comment by jakebian** [comment]
https://github.com/jakebian/quiver/pull/25 merged, @isaacgerg close this once you verify that the fix works for you

**Comment by isaacgerg** [comment]
@jakebian  Should I pull and  build through github or use pip?

**Comment by jakebian** [comment]
either should work!

**Comment by isaacgerg** [comment]
Pull 30 minutes ago.  This is not quite working yet.

The images at the layer look like they are rendering correctly, however, the classes are incorrect. Previously this tile was 99%+ school bus.  Now its nematode.


![image](https://cloud.githubusercontent.com/assets/11971499/20564807/da365cf6-b15c-11e6-9b3a-392253199d74.png)

**Comment by jakebian** [comment]
@isaacgerg that's a separate issue - unless you pass in a list of classes (see https://github.com/jakebian/quiver/pull/27), the imageNet classes will be used by default (a behavior we're going to deprecate soon), which looks like it's wrong in this case. The solution is to pass in a correct list of classes, or otherwise ignore this prediction feature.

**Comment by isaacgerg** [comment]
@jakebian I was loading the inception network with imagenet.
